version: '3.8'

services:
  django:
    build:
      context: ./django-repo
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-network

  playwright:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - django
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
