version: '3'
services:
  website:
    image: example_site_image:latest
    ports:
      - "8000:8000"
  test-framework:
    image: test_framework_image:latest
    depends_on:
      - website
    environment:
      BASE_URL: http://website:8000
