name: Deploy and Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-and-test:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Проверка репозитория с сайтом
      - name: Checkout site repository
        uses: actions/checkout@v3
        with:
          repository: Gygamyt/example_site_for_pipeline
          path: site

      # Шаг 2: Сборка и запуск контейнера с сайтом
      - name: Build and run website container
        run: |
          docker build -t site_image:latest ./site
          docker run -d --name site_container -p 8000:8000 site_image:latest

      # Шаг 3: Проверка репозитория с тестами
      - name: Checkout test framework repository
        uses: actions/checkout@v3
        with:
          repository: Gygamyt/example_test_framework_for_pipeline
          path: test-framework

      # Шаг 4: Сборка Docker-образа для тестов
      - name: Build test framework Docker image
        run: |
          cd test-framework
          docker build -t test_framework_image:latest .
        env:
          DOCKER_BUILDKIT: 1

      # Шаг 5: Запуск смоук-тестов
      - name: Run smoke tests
        run: |
          docker run --network="host" --name test_framework_container -v ${{ github.workspace }}/test-framework/reports:/app/playwright-report test_framework_image:latest --grep "smoke" --reporter=html

      # Шаг 6: Ожидание завершения смоук-тестов
      - name: Wait for smoke tests to complete
        run: |
          docker wait test_framework_container

      # Шаг 7: Копирование отчетов смоук-тестов из контейнера
      - name: Copy smoke test reports from container
        run: |
          mkdir -p playwright-reports/smoke
          docker cp test_framework_container:/app/playwright-report ./playwright-reports/smoke

      # Шаг 8: Удаление контейнера после смоук-тестов
      - name: Remove smoke test container
        run: |
          docker rm -f test_framework_container || true

      # Шаг 9: Запуск санити-тестов
      - name: Run sanity tests
        run: |
          docker run --network="host" --name test_framework_container -v ${{ github.workspace }}/test-framework/reports:/app/playwright-report test_framework_image:latest --grep "sanity" --reporter=html

      # Шаг 10: Ожидание завершения санити-тестов
      - name: Wait for sanity tests to complete
        run: |
          docker wait test_framework_container

      # Шаг 11: Копирование отчетов санити-тестов из контейнера
      - name: Copy sanity test reports from container
        run: |
          mkdir -p playwright-reports/sanity
          docker cp test_framework_container:/app/playwright-report ./playwright-reports/sanity

      # Шаг 12: Удаление контейнера после санити-тестов
      - name: Remove sanity test container
        run: |
          docker rm -f test_framework_container || true

      # Шаг 13: Установка `playwright-merge-reports` внутри контейнера
      - name: Install playwright-merge-reports
        run: |
          docker exec test_framework_container npm install -g playwright-merge-reports

      # Шаг 14: Объединение отчетов внутри контейнера
      - name: Merge Playwright reports inside container
        run: |
          docker exec test_framework_container npx playwright-merge-reports /app/playwright-report/smoke /app/playwright-report/sanity --output=/app/playwright-report/merged-report

      # Шаг 15: Копирование объединённого отчета из контейнера
      - name: Copy merged report from container
        run: |
          mkdir -p playwright-reports/merged
          docker cp test_framework_container:/app/playwright-report/merged-report ./playwright-reports/merged

      # Шаг 16: Сохранение объединённых отчетов как артефактов
      - name: Upload merged test reports
        uses: actions/upload-artifact@v3
        with:
          name: playwright-merged-reports
          path: playwright-reports/merged

      # Шаг 17: Проверка репозитория для отчетов
      - name: Checkout reports repository
        uses: actions/checkout@v3
        with:
          repository: Gygamyt/example_reports_gh_pages
          token: ${{ secrets.GH_PAT }}
          path: reports-repo

      # Шаг 18: Копирование отчетов в папку docs
      - name: Copy and rename test reports to docs folder
        run: |
          mkdir -p reports-repo/docs
          cp playwright-reports/merged/index.html reports-repo/docs/index.html

      # Шаг 19: Коммит и пуш отчетов
      - name: Commit and push reports
        run: |
          cd reports-repo
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update merged reports"
          git push

      # Шаг 20: Публикация на GitHub Pages
      - name: Deploy reports to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: reports-repo/docs

      # Шаг 21: Генерация ссылки на опубликованные отчеты
      - name: Generate merged test GitHub Pages URL
        id: merged-page-url
        run: |
          echo "GITHUB_MERGED_PAGES_URL=https://Gygamyt.github.io/example_reports_gh_pages/docs/merged-results.html" >> $GITHUB_ENV

      # Шаг 22: Вывод ссылки на опубликованные отчеты
      - name: Print merged test GitHub Pages URL
        run: |
          echo "Merged test reports are published at ${{ env.GITHUB_MERGED_PAGES_URL }}"
