name: Deploy And Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3

      - name: Clone other repository
        uses: actions/checkout@v3
        with:
          repository: MOCKMOCK
          path: MOCKMOCK

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r MOCKMOCK/requirements.txt

      - name: Run Migrations
        run: |
          cd MOCKMOCK/src
          python manage.py migrate

      - name: Collect Static Files
        run: |
          cd MOCKMOCK/src
          python manage.py collectstatic --noinput

      - name: Start server
        run: |
          cd MOCKMOCK/src
          python manage.py runserver 0.0.0.0:8000 &
          sleep 10

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Node.js dependencies
        run: |
          cd #тут надо КУДА
          npm install

      - name: Run Playwright tests
        run: |
          cd #просто в репе, райт?
          npx playwright test

      - name: Upload Allure results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: путь/к/папке/с/результатами

      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report