name: Deploy and Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Проверка репозитория с сайтом
      - name: Checkout website repository
        uses: actions/checkout@v3
        with:
          repository: Gygamyt/example_site_for_pipeline
          path: website

      # Шаг 2: Сборка Docker-образа для сайта
      - name: Build website Docker image
        run: |
          cd website
          docker build -t example_site_image:latest .
        env:
          DOCKER_BUILDKIT: 1

      # Шаг 3: Проверка репозитория с тестами
      - name: Checkout test framework repository
        uses: actions/checkout@v3
        with:
          repository: Gygamyt/example_test_framework_for_pipeline
          path: test-framework

      # Шаг 4: Сборка Docker-образа для тестов
      - name: Build test framework Docker image
        run: |
          cd test-framework
          docker build -t test_framework_image:latest .
        env:
          DOCKER_BUILDKIT: 1

      # Шаг 5: Запуск сайта
      - name: Run website container
        run: |
          docker run -d --name website_container -p 8000:8000 example_site_image:latest
        env:
          DJANGO_SETTINGS_MODULE: your_project.settings

      # Шаг 6.1: Проверка состояния контейнеров
      - name: List Docker containers
        run: |
          docker ps -a    

      # Шаг 6: Запуск тестов
      - name: Run tests
        run: |
          docker run --network="host" --name test_framework_container -v ${{ github.workspace }}/test-framework/reports:/app/playwright-report test_framework_image:latest
        env:
          BASE_URL: http://localhost:8000

      # Шаг 6.1: Проверка состояния контейнеров
      - name: List Docker containers
        run: |
          docker ps -a
      

    # Шаг 6.1: Копирование отчетов Playwright из контейнера
      - name: Copy Playwright reports from container
        run: |
          docker cp test_framework_container:/app/playwright-report ./test-framework-reports
      
      

        # Шаг 6.1: Проверка состояния контейнеров
      - name: List Docker containers
        run: |
          docker ps -a

      # Шаг 6.2: Ожидание завершения тестов
      - name: Wait for tests to complete
        run: |
          docker wait test_framework_container

      # Шаг 6.2: Проверка логов тестов
      - name: Check test logs
        run: |
          docker logs test_framework_container

        # Шаг 8: Сохранение отчетов Playwright как артефактов
      - name: Upload Playwright reports
        uses: actions/upload-artifact@v3
        with:
          name: playwright-reports
          path: test-framework-reports/

      # Шаг 9: Остановка и удаление контейнера сайта
      - name: Stop and remove website container
        run: |
          if [ $(docker ps -q -f name=website_container) ]; then
            docker stop website_container
            docker rm website_container
          fi

      # Шаг 10: Остановка и удаление контейнера тестов
      - name: Stop and remove test framework container
        run: |
          if [ $(docker ps -q -f name=test_framework_container) ]; then
            docker stop test_framework_container
            docker rm test_framework_container
          fi
