name: Deploy and Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  cache:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Проверка репозиториев и создание кэша
      - name: Checkout test framework repository
        uses: actions/checkout@v3
        with:
          repository: Gygamyt/example_test_framework_for_pipeline
          path: test-framework

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: |
            /tmp/docker-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker image with caching
        run: |
          docker buildx create --use
          docker buildx build --cache-to=type=local,dest=/tmp/docker-cache --cache-from=type=local,src=/tmp/docker-cache -t test_image:latest .

  smoke-tests:
    runs-on: ubuntu-latest
    needs: cache

    steps:
      - name: Checkout repositories
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t test_image:latest .

      - name: Run smoke tests
        run: docker run --name test_container test_image:latest --grep "smoke" --reporter=html

      - name: Save smoke test results
        run: |
          mkdir -p results/smoke
          docker cp test_container:/results /results/smoke

      - name: Upload smoke test results
        uses: actions/upload-artifact@v3
        with:
          name: smoke-results
          path: results/smoke

  sanity-tests:
    runs-on: ubuntu-latest
    needs: [cache, smoke-tests]

    steps:
      - name: Checkout repositories
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t test_image:latest .

      - name: Run sanity tests
        run: docker run --name test_container test_image:latest --grep "sanity" --reporter=html

      - name: Save sanity test results
        run: |
          mkdir -p results/sanity
          docker cp test_container:/results /results/sanity

      - name: Upload sanity test results
        uses: actions/upload-artifact@v3
        with:
          name: sanity-results
          path: results/sanity

  publish-reports:
    runs-on: ubuntu-latest
    needs: [smoke-tests, sanity-tests]

    steps:
      - name: Checkout reports repository
        uses: actions/checkout@v3
        with:
          repository: Gygamyt/example_reports_gh_pages
          token: ${{ secrets.GH_PAT }}
          path: reports-repo

      - name: Copy test results to reports
        run: |
          mkdir -p reports-repo/docs/smoke
          mkdir -p reports-repo/docs/sanity
          cp -r results/smoke/* reports-repo/docs/smoke
          cp -r results/sanity/* reports-repo/docs/sanity

      - name: Commit and push reports
        run: |
          cd reports-repo
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update test results"
          git push

      - name: Generate GitHub Pages URL
        id: page-url
        run: |
          echo "GITHUB_PAGES_URL=https://Gygamyt.github.io/example_reports_gh_pages" >> $GITHUB_ENV

      - name: Print GitHub Pages URL
        run: |
          echo "Reports are published at ${{ env.GITHUB_PAGES_URL }}"
