name: Deploy and Test

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Шаг 1: Проверка репозитория с сайтом
      - name: Checkout website repository
        uses: actions/checkout@v3
        with:
          repository: Gygamyt/example_site_for_pipeline
          path: website

      # Шаг 2: Сборка Docker-образа для сайта
      - name: Build website Docker image
        run: |
          cd website
          docker build -t example_site_image:latest .
        env:
          DOCKER_BUILDKIT: 1

      # Шаг 3: Проверка репозитория с тестами
      - name: Checkout test framework repository
        uses: actions/checkout@v3
        with:
          repository: Gygamyt/example_test_framework_for_pipeline
          path: test-framework

      # Шаг 4: Сборка Docker-образа для тестов
      - name: Build test framework Docker image
        run: |
          cd test-framework
          docker build -t test_framework_image:latest .
        env:
          DOCKER_BUILDKIT: 1

      # Шаг 5: Запуск Docker Compose
      - name: Run Docker Compose
        run: |
          docker-compose up -d

      # Шаг 6: Запуск тестов
      - name: Run tests
        run: |
          docker-compose run --rm test-framework

      # Шаг 7: Остановка и удаление контейнеров
      - name: Stop and remove containers
        run: |
          docker-compose down
