name: Deploy and Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      website:
        image: example_site_image:latest
        ports:
          - 8000:8000
        options: >-
          --env DJANGO_SETTINGS_MODULE=your_project.settings

    steps:
      - name: Checkout website repository
        uses: actions/checkout@v3
        with:
          repository: Gygamyt/example_site_for_pipeline
          path: website

      - name: Build website Docker image
        run: |
          cd website
          docker build -t example_site_image:latest .
        env:
          DOCKER_BUILDKIT: 1

      - name: Checkout test framework repository
        uses: actions/checkout@v3
        with:
          repository: Gygamyt/example_test_framework_for_pipeline
          path: test-framework

      - name: Build test framework Docker image
        run: |
          cd test-framework
          docker build -t test_framework_image:latest .
        env:
          DOCKER_BUILDKIT: 1

      - name: Run tests
        run: |
          docker run --network="host" test_framework_image:latest
        env:
          BASE_URL: http://localhost:8000
